### ISSUE TITLE
Please make fgrehm/vagrant-ubuntu a trusted build :-)

### ISSUE THREAD

**Issue by ches** [fgrehm/docker-provider#5]
I know that [you illustrate what this image is](https://github.com/fgrehm/docker-provider/tree/master/boxes/precise#readme) in the repo, but I had to poke around for a minute to realize that. If the README suggests installing your image as a quick start, it ought to be a [trusted build](http://blog.docker.io/2013/11/introducing-trusted-builds/), so people can be confident that what they're installing from the registry is actually built from the `Dockerfile` we think it is.

I think it'd also be helpful to add a quick sentence noting what this is, something like:

> The plugin is not very user friendly at the moment, so please download the base Docker image manually with `docker pull fgrehm/vagrant-ubuntu:precise` in order to have some feedback about the download process. **This image approximates standard Vagrant boxes (a `vagrant` user, with SSH key for `vagrant ssh`, etc.). It will be used by the box definition that you add below.**

**Comment by fgrehm** [comment]
Different from ventriloquist I can provide a trusted build for a single image, I'll do it :-)

**Comment by fgrehm** [comment]
[Done!](https://index.docker.io/u/fgrehm/vagrant-ubuntu/)

![image](https://f.cloud.github.com/assets/81859/2278647/1b16a13a-9f5a-11e3-95b8-6527f31ffb23.png)

I'm not sure that image will work with the current docker-provider released version but a new release is coming out (hopefully) tonight.

Thanks for reaching out :smiley:

**Comment by ches** [comment]
Yay, thanks!
