### ISSUE TITLE
Container is inaccessible from Mac (and Windows probably)

### ISSUE THREAD

**Issue by c10l** [fgrehm/docker-provider#9]
I had been fighting with this for a few days in the dark, but I found out why this was not working for me.

I am running it on a Mac, using [dvm](https://github.com/fnichol/dvm) as my docker host.

I can run docker commands just fine against it. Everything works, apart from networking.

Digging a bit the reasons became quite obvious and I'm not sure how to fix them. The problem is that the container's network is "host-only" with the docker server.

For this to work, this network has to be exposed to the docker host's host (my workstation).

From within the `dvm` guest, everything works as expected.

**Comment by fgrehm** [comment]
@cassianoleal Is there anything we can do from our side to make this work apart from writing docs?

**Comment by c10l** [comment]
I have no idea, to be honest... I've been thinking about this and I don't think so. It probably has to be fixed on -- or at least supported by -- the docker host (in this case a VirtualBox VM).

Feel free to close this if it makes sense. :)

**Comment by fgrehm** [comment]
No worries, I'll close this for now :-)

**Comment by fgrehm** [comment]
BTW, you might also want to give [boot2docker](https://boot2docker.github.io) a go

**Comment by c10l** [comment]
`dvm` actually uses boot2docker underneath...

Also judging by [this](https://github.com/boot2docker/boot2docker/blob/master/doc/WORKAROUNDS.md), it's very likely that it won't help much :)

**Comment by fgrehm** [comment]
That sucks =/
